### ISSUE TITLE
Can't initialise connection on Google Colab

### ISSUE THREAD

**Issue by rbeucher** [SlideRuleEarth/sliderule#440]
Hi, 

I am trying to run your examples using Google Colab but the connection fails to initialise.

```python
import sliderule
sliderule.init(url="slideruleearth.io", verbose=True)
```

returns:

```
Setting URL to slideruleearth.io
INFO:sliderule.sliderule:Setting URL to slideruleearth.io
Login status to slideruleearth.io/sliderule: failure
INFO:sliderule.sliderule:Login status to slideruleearth.io/sliderule: failure
True
```

**Comment by jpswinski** [comment]
@rbeucher thank you for reporting this issue - we have some work to do to make these messages more user friendly.

The login failure message is saying that you failed to login to the `slideruleearth.io/sliderule` cluster, which happened because you didn't have an account on our provisioning system for the `slideruleearth.io/sliderule` cluster.  But that is actually okay because the `slideruleearth.io/sliderule` cluster is a public cluster and therefore most of the APIs (and all of the ones you'd be interested in) do not need credentials to use.  The only APIs that failing to login would preclude are the ones related to changing the size of the cluster.

But for a private cluster (for example if you were logging into the University of Texas cluster at `slideruleearth.io/ut`), then a login failure prevents you from accessing any of the APIs, and the message is much more meaningful.

So these messages are very misleading for the public cluster and need to be changed.  Thank you for bringing this to our attention.  I'll make this change in the next release and notify you here.

**Comment by rbeucher** [comment]
Thank you @jpswinski.
I don't have that issue when I run the command on a local install of Jupyter. Why is that?
