### ISSUE TITLE
GEDI L2A no effect of degrade flags

### ISSUE THREAD

**Issue by ayush12gupta** [SlideRuleEarth/sliderule#446]
When using `gedi.gedi02ap` it has no effect when changing degrade flags. I also tried comparing the no. of GEDI points when read using the raw file and what sliderule returns, there is a difference in ones from sliderule and raw file with both degrade flag and without it. I have shown this issue in the notebook shared below.

https://notebooksharing.space/view/5b8da8ac5595d8d982df18174dc21b347ce23b2fb8d2659e0581a57f0d0b2cf0#displayOptions=
[mt_baker_area.zip](https://github.com/user-attachments/files/17739864/mt_baker_area.zip)

**Comment by scottyhq** [comment]
@ayush12gupta I see in your notebook you're setting degrade_flag=70. As far as I know it is a boolean value  see this discussion https://github.com/orgs/SlideRuleEarth/discussions/442

But in short, degrade_flag=0=False -> "not degraded" , degrade_flag=1=True -> "degraded quality"

**Comment by ayush12gupta** [comment]
@scottyhq Thanks for clarifying that, so when degrade filtering is used it is removing all non zero degrade flag values right ? 

However I am still wondering why the total no. of GEDI points are the same with and without degrade filter. And why there is difference in the total no. of GEDI points when read using raw files vs what sliderule returns.

**Comment by scottyhq** [comment]
> degrade filtering is used it is removing all non zero degrade flag values right ?

Yes, all degrade=1 values in theory. Maybe there is a bug though. In order to reproduce your examples, we'd need your polygon (/home/ayushg12/Desktop/UW_study/notebook/shapefiles/mt_baker_area.shp). So you can either print it out as text if it's simple, or just commit it to github (preferably as GeoJSON)!

**Comment by dshean** [comment]
Thanks @ayush12gupta for this example.  The last 3 cells are telling.  

Yes, this is potentially a bug.  We should revisit GEDI flags and how we're handling these on the server vs. client side.  Perhaps allowing users more granularity to specify filters if desired.  Definitely need to improve the doc around these topics.

@ayush12gupta:
- As scottyhq suggests, let's avoid shapefiles and stick with geojson whenever possible (though remember geojson spec only supports EPSG:4326, not projected CRS).
- Please use the sliderule `toregion` function (https://slideruleearth.io/web/rtd/api_reference/sliderule.html#toregion) to create polygons for your requests.  There is logic there to check and prepare polygons in expected format (e.g., winding order)
- You shouldn't need to add new columns for Longitude and Latitude - we intentionally strip these when creating the geometry column to reduce data volume. Though I understand you may be using these for plotting outside of geopandas.

**Comment by dshean** [comment]
> github doesn't supports geojson file type
Hmm.  Not sure I understand.  This is a text file, and Github should support natively (with preview).  For example: https://github.com/johan/world.geo.json/blob/master/countries.geo.json

**Comment by scottyhq** [comment]
Thanks @ayush12gupta 

I spoke too soon about my interpretation of degrade_flag. From sliderule's point of view degrade_flag=1 -> "degraded" for any reason, which according to [LPDAAC Data Dictionary](https://lpdaac.usgs.gov/documents/982/gedi_l2a_dictionary_P003_v2.html) can be due to many things.

Looks like these flag parameters were all updated recently in v4.8.0:
https://github.com/SlideRuleEarth/sliderule/blob/f8e233db85a105caf0bb08e501bcaa1fce4896d9/docs/rtd/source/release_notes/release-v4-8-0.md?plain=1#L37-L42

So I suggest changing your code to the following:

```python
# Note: .geojson instead of .geo.json :) 
aoi = gpd.read_file('mt_baker_area.geojson')


params ={
    "poly":sliderule.toregion(aoi)['poly'],
    "degrade_filter": True, # no degraded samples, 2547 points in aoi -> 232 points
}

gf = gedi.gedi02ap(params, resources=granules)
```

**Comment by ayush12gupta** [comment]
Ok got it, just need to change the flag parameters. Thanks!
